---
- name: Create node_exporter user
  become: true
  user:
    name: node_exporter
    shell: /bin/false
    system: yes
    comment: "Node Exporter User"

- name: Download node_exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract node_exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/opt"
    remote_src: true
- name: Copy node_exporter binary to /usr/local/bin
  become: true
  copy:
    src: /opt/node_exporter-1.2.2.linux-amd64/node_exporter
    dest: /usr/local/bin/
    remote_src: true   
- name: Create systemd service file for node_exporter
  copy:
    src: /home/Ansible/node_exporter/templates/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Restart and enable node_exporter service
  become: true
  systemd:
    name: node_exporter.service
    state: restarted
    enabled: yes
