---
- hosts: kibana
  remote_user: artem
  become: yes
  become_user: root
  tasks:
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Pull Kibana container
      docker_image:
        name: kibana
        source: pull

    - name: Run Kibana container
      docker_container:
        name: kibana
        image: kibana
        ports:
          - "5601:5601"
        depends_on:
          - elasticsearch    